controle_horas/urls.py
from django.urls import path
from . import views

app_name = 'controle_horas'

urlpatterns = [
    path('', views.index, name='index')
]

gerador/urls.py
from django.urls import path
from . import views

app_name= 'gerador'

urlpatterns = [
    path('', views.index, name='index'),
    path('atualizar/', views.number, name='atualizar')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

miniprojetos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('gerador/', include('gerador.urls')),
    path('controle_horas/', include('controle_horas.urls'))
]

controle_horas/models.py
from django.db import models

# Create your models here.
class Horas(models.Model):
    entrada_inicial = models.DateTimeField()
    saida_inicial = models.DateTimeField()
    entrada_final = models.DateTimeField()
    saida_final = models.DateTimeField()

controle_horas/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'controle_horas/index.html')

gerador/views.py
from django.shortcuts import render
import random
from django.http import JsonResponse

# Create your views here.
def index(request):
    return render(request, 'gerador/index.html',{
    })
def number(request):
    numbers = [random.randrange(1,60,1)for i in range (6)]
    #list comprehension
    #gerando numeros aleatórios de 1 a 60 (1 é o intervalo)
    return JsonResponse({'numeros':numbers})

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home/index.html")

controle_horas/templates/controle_horas/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Controle de Horas</title>
</head>
<body>
    <h1>it's working</h1>
</body>
</html>

gerador/templates/gerador/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Gerador</title>
    <link rel="stylesheet" href="{% static 'gerador/style.css'%}">
</head>
<body>
    <div class="container">
        <h1>Gerador</h1>
        <div class="box-numbers">
            <div class="numbers">
                <h4>LUCKY</h4>
                <h4>6 numeros da sorte gerados aleatóriamente!!!</h4>
            </div>
            <div class="button">
                <button id="refresh">Gerar</button>
            </div>
        </div>
        <h5><a href="{%url 'home:index'%}">VOLTAR</a></h5>
    </div>
    <script>
    let caixa = document.querySelector(".numbers")
        document.addEventListener('DOMContentLoaded', function(){
    document.getElementById('refresh').addEventListener('click', function(){
        caixa.innerHTML = ""
        caixa.style.flexDirection = "row";
    fetch("{% url 'gerador:atualizar' %}")
    .then(response => response.json())
    .then(data => 
        data.numeros.forEach(numero => {
        let h5 = document.createElement("h5")
        h5.classList.add("number");
        h5.innerHTML = numero
        caixa.appendChild(h5);
        })); 
    })
    });
    </script>
</body>
</html>

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>HOME</title>
    <link rel="stylesheet" href="{% static 'home/style.css'%}">
</head>
<body>
    <div class="container">
        <div class="projectslist">
            <div class="head">
            <h1>Mini Projects List</h1>
            </div>
            <div class="lista">
                <ol>
                    <li><a href="{% url 'gerador:index' %}">Gerador de Apostas</a></li>
                    <li><a href="{% url 'controle_horas:index' %}">Controle de Horas</a></li>
                    <li>Rank de Filmes</li>
                    <li>Encurtador de URLs</li>
                    <li>Sistema de Autenticação</li>
                </ol>    
            </div>
        </div>
    </div>
</body>
</html>